travis:
  secure:
    BINSTAR_TOKEN: UhEtrvkVCWiyGguX3FI8aM6/9J7wRwo9Ebxd34bsCye2bs4vNOtiLgAaN7N0mFstjIeC58/TplOcS93ozzDa6fo5FELueORTAJmlXJaT5tTFRfN8kiIyaCT1mUb8lq5u91CgXujAyJauk3LwvSpd3sL4m5W31nk4yzralAyYXbokjrcgsgGDoPZheTMvwVMxgOYcQ0tKuaxyHBvdhxAcBmYaVdbTP3V/L+djXlMwis9GpEzM88CR3AqCdhSiTsRY9tS2xY4OfExS2L+TUG3ozm4Of33ygzextAn0HIZl/pAQyI0hBsoy4JAW6gmxAC3oKGATQzf/B+EMZ/heVZ3Y666kxFdym91mk4sx860BiNcEHVElHVl+2/cKacmp128SC8wM79TY7ys/hbhFsIT93TDPBa1v+m1qS0NwRF0z1qXQaAPlxXU+dWXwyeBifJ3f8BVFvPbq9y4eaoV1B2PGs2FpvoMbZbIBBKo9o3taOapLfTPnzArDwh5mZaZAMFYaN1cYet/tSKSax075Fdmy1yexRBVoGrBxioL661eHRTPSgqJPvfxTSL/upJSng4G7vaA7SzNbe6awUmD0Z/sCN/+5B/Nv6hJ+5MLjRfreNOVYjb9dtNIGMD11mp7Aa4TXuPdDSLUehT/mw15QURfU2QSz6zA9OugXG4KvKtBmXmk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
