travis:
  secure:
    BINSTAR_TOKEN: zEA5+NNANgbpt1cmLbNbcxrYQE+z5tPPVnwJXk02CaGCALoHmq7s3dAFccYV8uk/fjpNDR4Arr1a86v8mJ90QJGCPigPi8LWeAF38NqbdfaJ5qDMqpBTZDg+X95kQpUZubt6+2hM8vHoVaAX5mn9nLZIyNY54uX9NesVollmUauznnktz6zR3OvFServMdm3booYZvpWhYTE0yDUgev3uOid1wD+cBOlesEiUcctdziIK08OPUzddttoAWV/x6iKZdeQ+wrxm0Ftlqc9tE6ETEyRQMSxQQ/ygEKYVH3QiQRxtXOfAnlZB7XvVIe4hpatcTms4LpHDuFgE688knvXAd4vl4koKHlW7iKVF78Pn5ruliMmY9Gt2RWq5UrJHC1CBVatkbM+LGoAwLNdoQHFbbK2mHgIlp6af3W+sJy3BwkAc00DqHgZllFYWvF0x1czL+iwRe3uqEQRb+y9bj1w0SqSHUHQmViegvGe2zwQLBxfP3IoGnhFcPikO3Abu/LvhTEMqfC8dVCelUP3MrKKOvtIfTBeLO4XFmVvp2Ng8ofP3LWMNH6Foh11cBU13yVkEmA4kC7o7tqgT5P7Oosvne7tvX2zlbYr8wQLM8SCmm5p0nrRKxHZ1hm6DgmyZ64RBwXIC4aXWCYgL3Ik5y7nHuNJE+RbvM7Idbs7eed3Z5g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
